services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
     - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
    env_file:
      - ../.env
    develop:
      watch:
        - path: ../requirements.txt
          target: /app
          action: rebuild
        - path: ..
          target: /app
          action: sync

volumes:
  postgres_data:
    name: postgres_data
    external: true

networks:
  mynetwork: