# Generated by Django 4.2 on 2023-07-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_asset_assetbalance_assetbalancehistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('api_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='assetbalancehistory',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=19),
        ),
        migrations.CreateModel(
            name='AssetPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=19)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.asset')),
            ],
        ),
        migrations.AddField(
            model_name='assetbalance',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.exchange'),
        ),
    ]
