# Generated by Django 4.2 on 2023-07-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_exchange_api_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetbalancehistory',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='assetpricehistory',
            options={'ordering': ['date']},
        ),
    ]
