# Generated by Django 4.2 on 2023-07-20 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0006_alter_assetbalancehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(default='asset', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetbalancehistory',
            name='balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.assetbalance'),
        ),
        migrations.CreateModel(
            name='ApiConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=256)),
                ('secret_key', models.CharField(max_length=256)),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.exchange')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
