# Generated by Django 4.2 on 2023-07-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_asset_type_alter_assetbalancehistory_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='type',
            field=models.CharField(blank=True, choices=[('brokerage_house', 'Brokerage House'), ('crypto_exchange', 'Cryptocurrency Exchange')], max_length=16),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, choices=[('stock', 'Stock'), ('cryptocurrency', 'Cryptocurrency'), ('cash', 'Cash')], max_length=16),
        ),
    ]
