# Generated by Django 4.2 on 2023-07-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_exchange_type_alter_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('stock', 'Stock'), ('cryptocurrency', 'Cryptocurrency'), ('cash', 'Cash')], max_length=16),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='type',
            field=models.CharField(choices=[('brokerage_house', 'Brokerage House'), ('crypto_exchange', 'Cryptocurrency Exchange')], max_length=16),
        ),
    ]
