# Generated by Django 4.2 on 2023-07-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_assetbalancehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetbalance',
            options={'ordering': ['asset']},
        ),
    ]
