# Generated by Django 4.2 on 2023-07-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_assetbalance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetbalancehistory',
            options={'get_latest_by': ['date'], 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='assetpricehistory',
            options={'get_latest_by': ['date'], 'ordering': ['date']},
        ),
    ]
