# Generated by Django 4.2 on 2023-08-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_assetbalancehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='api_name',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
