# Generated by Django 4.2 on 2023-08-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_asset_api_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='api_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
