# Generated by Django 4.2 on 2023-08-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_asset_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='assetbalancehistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
