# Generated by Django 4.2 on 2023-08-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_asset_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='icon',
            field=models.ImageField(null=True, upload_to='portfolio/static/media/images/assets/crypto'),
        ),
    ]
