# Generated by Django 4.2 on 2023-08-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_asset_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbalancehistory',
            name='date',
            field=models.DateField(),
        ),
    ]
