# Generated by Django 4.2 on 2023-08-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_assetbalancehistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/static/media/images/assets/crypto'),
        ),
    ]
