# Generated by Django 4.2 on 2023-09-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_exchange_type_alter_exchange_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name']},
        ),
    ]
