# Generated by Django 4.2 on 2023-10-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_asset_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='icon',
        ),
    ]
