# Generated by Django 4.2 on 2023-09-12 09:22

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_asset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.asset_icon_path),
        ),
    ]
