# Generated by Django 4.2 on 2023-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_remove_asset_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='slug',
            field=models.SlugField(default='slugdefault', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='slug',
            field=models.SlugField(default='slugdefault', unique=True),
            preserve_default=False,
        ),
    ]
